# Basic Configuration
baseURL = "https://respiroc.com/"
languageCode = "nb-NO"
title = "Respiro"

# Core SEO switches
enableRobotsTXT = true

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.148.2"

# Use Git/file times for <lastmod> in pages and sitemap
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML, important for JSON-LD etc.
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[minify]
  minifyOutput = true

[menus]
  [[menus.main]]
  name = 'Contact us'
  url = '/pages/contact-us/'
  weight = 1

  [[menus.main]]
  name = 'About us'
  url = '/pages/about-us/'
  weight = 2

  [[menus.main]]
  name = 'Marketing blog'
  url = '/blogs/marketing/'
  weight = 3

[params]
  description = 'Respiro AS is a software development company focusing on "AI first" systems.'
