baseURL = "https://respiroc.com/"
languageCode = "en-US"
title = "Respiro"

theme = "r-hugo-theme"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]
enableGitInfo = true # Use Git/file times for <lastmod> in pages and sitemap

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Allow raw HTML, important for JSON-LD etc.

[minify]
minifyOutput = true



[params.header]
brandIconClass = "bi-cpu-fill"
[params.header.cta]
text = "Get in touch"
url = "/pages/contact/"

[params.company]
name = "Respiro"
address_lines = ["Oslo, Norway"]
orgnr = ""
orgform = "Private company"

[params.footer]
[params.footer.about]
text = "Respiro is an AI-first software company building products that help teams work smarter and move faster."

[params.contact]
email = "hello@respiroc.com"
orgnr = ""
address = "Oslo, Norway"
phone = "+47 00000000"
contact_form_url = "/pages/contact/"

[[params.contact.opening_hours]]
days = "Monday - Friday"
hours = "09:00 - 17:00"

[[params.contact.opening_hours]]
days = "Saturday"
hours = "10:00 - 14:00"

[[params.contact.opening_hours]]
days = "Sunday"
hours = "Closed"
closed = true

[params.services]
intro_title = "What we build"
intro_text = "Respiro creates AI-first SaaS that augments workflows with intelligent automation, copilots, and secure data pipelines."

[menu]
[[menu.main]]
name = "Blog"
url = "/blogs/marketing/"
weight = 10

[[menu.main]]
name = "About"
url = "/pages/about-us/"
weight = 20

[[menu.main]]
name = "Contact"
url = "/pages/contact/"
weight = 30

[[params.services.features]]
title = "AI-first by design"
description = "We design around intelligent agents and copilots from day one, not as an add-on."

[[params.services.features]]
title = "Secure and compliant"
description = "Enterprise-ready foundations with auditability, privacy, and data governance."

[[params.services.features]]
title = "Measurable impact"
description = "We focus on outcomes: reduced cycle time, higher conversion, and better customer experiences."

[[params.faq]]
q = "What does AI-first mean at Respiro?"
a = "AI shapes product architecture, UI, and workflows—every feature is evaluated for how intelligent automation can create leverage."

[[params.faq]]
q = "Do you work with existing tools?"
a = "Yes. Our products integrate with popular CRMs, data warehouses, and analytics platforms."

[[params.faq]]
q = "Where are you based?"
a = "We are based in Oslo, Norway with distributed team members."

[[params.faq]]
q = "How can we contact you?"
a = "Email hello@respiroc.com or use the contact page."
